---
- name: Configure OSPF on ALL
  hosts: routers
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_user: cisco
    ansible_password: cisco
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco
  tasks:
    - name: enable OSPF
      ios_config:
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
      register: print_output

    - name: Display the output
      debug:
        var: print_output
