---
- name: Configure OSPF on ALL
  hosts: routers
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios
    ansible_user: cisco
    ansible_password: cisco
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco

  tasks:
    - name: remove EIGRP
      ios_command:
        commands:
          - conf t
          - no router eigrp 1
      register: print_output

    - debug:
        var: print_output
